### ISSUE TITLE
Aprendendo Polymer - Todo List.

### ISSUE THREAD

**Issue by MTAugusto** [brainstormspace/studyspace#1]
Autores : @LaynerClever  , @halyson97 , @luizalexandrew .
Recursos: 
1 - Ser um aplicativo Android feito em Cordova (Obrigatório kkkk).
2 - Salvar todas as notas no LocalStorage e recupera-las. (Obrigatório kkkk)
3 - Notas com cor.
4 - Notas com  @Categoria.(Dinâmica ou previamente definidas pelo app).
5 - Excluir nota arrastando :).
6 - Editar nota .
7 - Implementar uma SPA (Single Page Application).

OBS: Fazer no minimo 5 itens a sua escolha :). 
OBS: Fazer no horário de serviço automaticamente perde a aposta kkkkkkkk.

**Comment by luizalexandrew** [comment]
Tá saindo da jaula kkkk

![captura de tela de 2017-01-22 22-27-07](https://cloud.githubusercontent.com/assets/10445220/22187679/efcee096-e0f1-11e6-9752-fe1c2b35ef05.png)
